### ISSUE TITLE
Incorrect values in the year columns

### ISSUE THREAD

**Issue by yufenghe22** [biocro/biocro#126]
It seems that all the `year` columns have the value `2000` in the weather data, including `cmi_weather_data.rdata` and `soybean_weather.rdata`.

This does not impact the biocro_run results if the actual weather data is indeed for each year. Then it would be just to update the `year` columns to reflect the correct year.

**Comment by justinmcgrath** [comment]
This looks like a issue that was introduced when rounding the weather data. The section in inst/extdata/rounding_weather_values.R should not round the year.

**Comment by justinmcgrath** [comment]
Ed is pretty busy at the moment so I don't think he'll get to this soon. Is this something you could work on?

**Comment by yufenghe22** [comment]
> Ed is pretty busy at the moment so I don't think he'll get to this soon. Is this something you could work on?

Yes. I'll make a PR to fix this.

**Comment by eloch216** [comment]
There is another weather-related issue: the weather data for 2023 is, unintentionally, a copy of the 2022 weather data. You can verify by typing `all(BioCro::weather[['2022']] == BioCro::weather[['2023']])`.

This was related to a mistake in the weather data repository code, which has since been fixed: https://github.com/eloch216/oscillator-based-circadian-clock-analysis/commit/b3ee327bf519ff4b0dc3c5489bb02502ab61ae64

So, it would be good to get a fresh copy of ``cmi_weather_data.RData` from the main branch of `eloch216/oscillator-based-circadian-clock-analysis` when fixing the year issue.

**Comment by yufenghe22** [comment]
I have made a PR to fix this.
