### ISSUE TITLE
Eliminate use of Variable-length arrays?

### ISSUE THREAD

**Issue by gsrohde** [biocro/biocro#69]
Four files in the module library use variable-length arrays.  This is a feature that was added to C99 but was not added to the C++ standard, and using the `-Wvla flag` when compiling (you can add this to the `PKG_CPPFLAGS` variable in Makevars) will warn about it.  The files and variables are

* `AuxBioCro.cpp`: `rootDist`
* `CanAC.cpp`: `wind_speed_profile` and `leafN_profile`
* `c3CanAC.cpp: `wind_speed_profile` and `leafN_profile`
* `multilayer_canopy_properties.cpp`: `wind_speed_profile` and `leafN_profile`

Shall we replace these C arrays with `vector` or some other form of dynamic array?  As yet, the code continues to compile on the platforms we're testing and using.

**Comment by justinmcgrath** [comment]
These were all in C before, which explains why they're there. Since every major compiler permits them and are probably going to forever, I don't see this as a priority. However, slowly these are going to be replaced, and it's probably best to avoid VLAs in any new code. If replacing VLAs here with vectors is particularly simple, then I see no harm either way.

**Comment by justinmcgrath** [comment]
This comes up as a warning when submitting to CRAN, so let's fix it and make it high priority since this appears to be the only thing keeps us off CRAN now. I looks like using vectors is the simplest approach. Whatever works is fine though.

**Comment by justinmcgrath** [comment]
Fixed in #100.
