### ISSUE TITLE
par energy content

### ISSUE THREAD

**Issue by uphone87** [biocro/biocro#74]
According to [Table 2 on Page 3 in this book](https://www.controlledenvironments.org/wp-content/uploads/sites/6/2017/06/Ch01.pdf), the conversion rate from PAR Photon (400-700nm) to Watt should be no more than 0.219 (=1/4.57), compared with 0.235 as what's been used in our model.

Should we change it?

@gsrohde @eloch216 @justinmcgrath @leighmatth Sorry, I at you here since I can't add assignees somehow.

**Comment by eloch216** [comment]
I checked the Campbell & Norman textbook too. It uses 1/4.6 = 2.17 (see page 149). The SURFRAD README file also uses that conversion.

I am not sure where 0.235 came from. I can see it all the way back in the old Wimovac Visual Basic code, but it doesn't cite a source. I will check the Humphries thesis next to see if there are any clues there.

I think it's probably fine to change -- I wouldn't expect it to have a big impact on anything, and it would be nice to have a source we could cite for that number. It would be good to double-check that it doesn't have a big impact. It also may necessitate a re-parameterization of the soybean model. (Although any changes will probably be small.)

**Comment by eloch216** [comment]
I didn't find anything helpful in the thesis, but did find something in the Monteith & Unsworth textbook. See page 69 in this PDF: https://denning.atmos.colostate.edu/readings/Monteith.and.Unsworth.4thEd.pdf

It says: "At a given site, the relation between quantum content and energy appears to be conservative. McCartney (1978) reported a value of 4.56 ± 0.05 μmol J−1 (PAR) in the English Midlands. This is equivalent to about 2.3 μmol J−1 total (global) radiation but other values reported range from 2.1 μmol J−1 in California to 2.9 μmol J−1 in Texas (Howell et al., 1983). The ratio of quantum content to energy in the PAR waveband for diffuse radiation from a cloudless sky is smaller than that for total radiation, about
4.25 μmol J−1 PAR, because quanta at shorter wavelengths carry more energy than those at longer wavelengths."

4.25 micromol per Joule is about 0.235 J per micromol, so I guess this is where the number came from.

**Comment by eloch216** [comment]
It sounds like 0.235 might be appropriate for an extremely clear sky, while the smaller number (0.217 or 0.219) would be more appropriate for slightly cloudy or dusty skies. I think it's rare to have such a clear sky, so the smaller values might be better to use. (This seems similar to the atmospheric transmittance value that was also originally set to a value that would only be appropriate for a ridiculously clear sky.)

**Comment by uphone87** [comment]
Thanks for the references @eloch216. I vote for changing it to 0.219.

I just tested the par energy content of 0.219 and it showed little impact on canopy assimilation and yield. As I suspected, it mostly impacted the canopy transpiration (cuz this constant is found in that module) by ~1% for the accumulative transpiration.

I'm bringing this up because sometimes we need to convert the PAR (in W/m2) to μmol m-2 s-1. Here a commonly used constant is 4.57 or 4.6. The inverse of 4.57 is 0.219. I think these two conversion needs to be consistent to make sure energy is conserved.

**Comment by justinmcgrath** [comment]
> I'm bringing this up because sometimes we need to convert the PAR (in W/m2) to μmol m-2 s-1. Here a commonly used constant is 4.57 or 4.6. The inverse of 4.57 is 0.219. I think these two conversion needs to be consistent to make sure energy is conserved.

Regardless which value is used, can we change the models so that there is only one parameter, using the inverse where necessary? That would make things consistent and a bit simpler.

**Comment by uphone87** [comment]
> > I'm bringing this up because sometimes we need to convert the PAR (in W/m2) to μmol m-2 s-1. Here a commonly used constant is 4.57 or 4.6. The inverse of 4.57 is 0.219. I think these two conversion needs to be consistent to make sure energy is conserved.
> 
> Regardless which value is used, can we change the models so that there is only one parameter, using the inverse where necessary? That would make things consistent and a bit simpler.

The issue is that BioCro's input PAR is in μmol m-2 s-1. So a conversion from W/m2 is required before BioCro. For example, if someone downloads NASA data and it needs to be converted first for running BioCro. They may not be aware of what BioCro  uses for this constant. One solution is that we start using W/m2 as input for BioCro, which I believe is a more commonly used SI unit for radiation.

**Comment by eloch216** [comment]
> > > I'm bringing this up because sometimes we need to convert the PAR (in W/m2) to μmol m-2 s-1. Here a commonly used constant is 4.57 or 4.6. The inverse of 4.57 is 0.219. I think these two conversion needs to be consistent to make sure energy is conserved.
> > 
> > 
> > Regardless which value is used, can we change the models so that there is only one parameter, using the inverse where necessary? That would make things consistent and a bit simpler.
> 
> The issue is that BioCro's input PAR is in μmol m-2 s-1. So a conversion from W/m2 is required before BioCro. For example, if someone downloads NASA data and it needs to be converted first for running BioCro. They may not be aware of what BioCro uses for this constant. One solution is that we start using W/m2 as input for BioCro, which I believe is a more commonly used SI unit for radiation.

Weather data will always be a PITA because there are many different sources for it, and they are not consistent with their formatting, units, etc. For light intensity, W / m^2 vs. micromol / m^2 / s is more than a question of units, and the appropriate type depends on the calculation in question. E.g. for photosynthesis calculations, a quantum flux needs to be used (because we know photosynthesis rates depend on number of photons more directly than energy). But for transpiration, an energy flux needs to be used because these calculations are based on energy balance.

BioCro's modular approach allows us to use different modules with different weather data sets. This is flexible, and in my opinion, the best way to go about doing it. For example, if a weather set already has separate diffuse and direct radiation components, then the `BioCro:incident_shortwave_from_ground_par` module can be removed.

So, for this issue, I would suggest simply adding a module that converts an above-canopy PAR from W / m^2 to micromol / m^2 / s. It would have `solar` as an output quantity and `par_energy_content` as an input quantity. People using NASA weather data will use this module. Others using other data sets won't need it. Then no other calculations or modules need to change.

**Comment by uphone87** [comment]
This issue has been resolved in a related [PR](https://github.com/biocro/biocro/pull/76).
